version: '3.1'
services:

  db:
    image: mariadb:5.5
    container_name: satnogs_db_mysql
    environment:
    - MYSQL_DATABASE=satnogsdb
    - MYSQL_USER=satnogsdb
    - MYSQL_PASSWORD=satnogsdb
    - MYSQL_ROOT_PASSWORD=toor

  redis:
    image: redis:3.2.8
    container_name: satnogs_db_redis

  celery:
    build:
      context: .
      dockerfile: docker/dev
    container_name: satnogs_db_celery
    volumes:
      - .:/app
    links:
      - db
      - redis
    environment:
      - DATABASE_URL=mysql://satnogsdb:satnogsdb@db/satnogsdb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command:
      ./bin/run-celery.sh

  web:
    build:
      context: .
      dockerfile: docker/dev
    container_name: satnogs_db_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db
      - redis
    environment:
      - DATABASE_URL=mysql://satnogsdb:satnogsdb@db/satnogsdb
    command:
      ./bin/run-web.sh
